### ISSUE TITLE
maybe all the "rand_num" functions can be combined as a big one

### ISSUE THREAD

**Issue by psli01** [JarvisXX/NumGuess#2]

**Comment by elicassion** [comment]
Yeah, I agree with brother shuai.
But, what is so-called 'big one'?  Combining functions into a big one is useless, while it's better to design it as a function satisfying general cases.

**Comment by owenzx** [comment]
Yes, there're many similar statements in these three functions. You'd better design a new one which is more POWERFUL!

**Comment by JarvisXX** [comment]
Nice suggestion,guys. Thank you.
